### PR TITLE
Fix ped bugs: Leng Khai

### LINKED ISSUE #333: [PE-D][Tester C] Name of Length 1 cannot be entered
## Describe the bug
When name is of length 1, I am unable to insert the person into the list.

## Expected behavior
Suppose to be able to enter as people can have 1 letter names.

## Priority
P02, if users have only 1 letter name cannot enter.

## Screenshots/Video

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: headcube1/ped#1

### LINKED ISSUE #339: [PE-D][Tester C] deleteShown Command Issue
## Describe the bug
If only 1 person is inside the list, after I conduct a find on the person, I want to deleteShown. However, I am unable to do so.

## Expected behavior
Expect to be able to delete the person and the empty list would be shown.

## Priority
P1, only if the list has 1 person.

## Screenshots/Video

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: headcube1/ped#4

### LINKED ISSUE #347: [PE-D][Tester C] Unable to Import Exam Scores
## Describe the bug
Even when email is in the first column, unable to import CSV file.

## Expected behavior
Suppose to be able to import then ignore all the inputs.

## Priority
P1, Unable to import Exam Scores.

## Screenshots/Video

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: headcube1/ped#5

### LINKED ISSUE #360: [PE-D][Tester C] Incorrect Error Upon Import of Exam Scores
## Describe the bug
When entering an invalid score, the error message shown is that the score is not a valid number, but in fact it is.

## To Reproduce
CSV file has a large number
## Expected behavior
Error should be invalid score.

## Screenshots/Video

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: headcube1/ped#8

### LINKED ISSUE #361: [PE-D][Tester C] Error message Incorrect Upon Import of Exam Scores when email is empty
## Describe the bug
When no email is entered, the error message still score is not a number when the number is too large.

## To Reproduce
The csv file does not have any email with a large score value.
## Expected behavior
Expect an error message of email not present.

## Screenshots/Video

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: headcube1/ped#9

### LINKED ISSUE #369: [PE-D][Tester B] `importExamScores` command not responding when parameter contains the `"` character
## Steps to reproduce

1. Run the application.
1. Enter the command `import i|"`

## Expected

The following message is displayed:

```
Invalid command format! 
importExamScores: Imports exam scores from specified filepath. Must be an absolute CSV file path. Parameter: i|FILEPATH
Example: importExamScores i|C:usr/lib/text.csv
```

## Actual

No message is displayed.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chin-herng/ped#3

### PR DESCRIPTION
**Pull request by Zer0Legion**
1. Fixed importExamScores functionality and error reporting
2. Changed Name and Exam to allow for 1 char name

Fixes #369
Fixes #361
Fixes #360
Fixes #347
Fixes #333
Fixes #339

### CODE REVIEW

**Review by delishad21 — COMMENTED** [review]
Good bugfixes! Lets continue to keep our code bug free!

File: src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java [hunk 1]
```diff
@@ -23,25 +23,27 @@ public class ImportExamScoresCommand extends Command {
 
     public static final String COMMAND_WORD = "importExamScores";
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Imports exam scores from specified filepath."
-            + " Must be an absolute CSV file path. Parameter: "
+            + " Must be an absolute CSV file path without any inverted commas. Parameter: "
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java:26]: These changes definitely help with the clarity of the `importExamScore` command

**Review by jayllo-c — COMMENTED** [review]
Both of these issues have been solved with this PR

- Fixed importExamScores functionality and error reporting
- Changed Name and Exam to allow for 1 char name
