### PR TITLE
fix: change unique parameter of persons in the addressbook to email

### LINKED ISSUE #95: Change unique parameter to email
Current program sets the unique parameter as name instead

### PR DESCRIPTION
**Pull request by danielleloh**
initially the unique parameter of persons in the addressbook was the name of the person. however, it does not make sense for the name of the person to be unique as it is not uncommon for 2 persons in the cohort to have the same name. therefore, we changed the unique parameter to the email address of persons as 2 students in a cohort should not have the same email address.

change,
* method in Person class that compares two persons if they are equal to compare the email address of the persons instead of the name
* error message of the addressbook to warn users of a duplicate email address in a contact they attempt to add

fixes #95 

## other changes in later commits:
* change email address to be case-insensitive as john@example.com should be equal to John@example.com, so that two similar emails with different letter casing will not be accepted by the addressbook
* change tests to achieve higher test coverage for the fix of changing unique parameter to email address instead of name

### CODE REVIEW

**Review by jayllo-c — COMMENTED** [review]
It looks good to me, the changes made would allow the unique parameter to shift from name to email with minimal edits to the code. The test code has also been updated properly. Great job!

**Review by Zer0Legion — COMMENTED** [review]
LGTM

**Review by delishad21 — COMMENTED** [review]
LGTM

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -39,7 +39,7 @@ public class AddCommand extends Command {
             + PREFIX_TAG + "owesMoney";
 
     public static final String MESSAGE_SUCCESS = "New person added: %1$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book";
+    public static final String MESSAGE_DUPLICATE_EMAIL = "This email already exists in the address book";
```
Comment (Zer0Legion) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:43]: Although the change seems basic, it requires a high level of attention to detail, so that minute changes like this can be implemented.

**Comment by Pughal77** [comment]
Nice! good to keep our naming consistent
