### PR TITLE
Modify AddCommand to throw more specfic exceptions

### LINKED ISSUE #292: Improve AddCommandParser error messages
Right now when the user gives an input with any of the compulsory parameters missing, it does not tell the user which fields are missing or not recognised. Lets improve the error reporting for addCommand!

### PR DESCRIPTION
**Pull request by delishad21**
Currently, the AddCommandParser throws a very generic message when compulsory prefixes are missing from the user input. Lets change it so that it indicates which compulsory prefix is missing. This will also benefit the Import Command when it generates its error report.

Fixes #292

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -46,9 +49,18 @@ public AddCommand parse(String args) throws ParseException {
...
 
-        if (!arePrefixesPresent(
-                argMultimap, PREFIX_NAME, PREFIX_ADDRESS, PREFIX_PHONE, PREFIX_EMAIL)
-                || !argMultimap.getPreamble().isEmpty()) {
+        List<Prefix> missingCompulsoryPrefixes = findMissingCompulsoryPrefixes(argMultimap, PREFIX_NAME, PREFIX_PHONE,
+                PREFIX_EMAIL, PREFIX_ADDRESS);
+
+        if (missingCompulsoryPrefixes.size() > 0) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                                                    MESSAGE_MISSING_COMPULSORY_PREFIXES
```
Comment (Zer0Legion) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:57]: Very clean way of catching which prefixes are missing!

File: src/main/java/seedu/address/storage/JsonAdaptedExam.java [hunk 2]
```diff
@@ -42,6 +45,23 @@ public String getMaxScore() {
...
-        return new Exam(ParserUtil.parseExamName(name), ParserUtil.parseScore(maxScore));
+
+        if (name == null) {
+            throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT, "name"));
+        }
+        if (Exam.isValidExamName(name) == false) {
+            throw new IllegalValueException(Exam.MESSAGE_CONSTRAINTS);
+        }
+        if (maxScore == null) {
+            throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT, "maxScore"));
```
Comment (jayllo-c) [inline src/main/java/seedu/address/storage/JsonAdaptedExam.java:56]: Great job separating the different errors that can be generated

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Comment (jayllo-c) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:1]: Good job changing the unit tests to match the changes made

**Review by jayllo-c — COMMENTED** [review]
The changes made will definitely help the user to understand where the command went wrong, which will improve the user experience
