### PR TITLE
Bug fix: import command 

### LINKED ISSUE #165: Bug fixes for import command
Currently the import command has the following bugs:
- does not check if the file is a csv file or not
- it does not check if the first line is a header or not
- when a duplicate person is found, instead of importing the other contacts, the app just throws an error

### LINKED ISSUE #167: Give a report for import command
To include for the cases where some contacts are duplicate and some are not, instead of throwing an error until the first duplicate contact is found, it is better to give a report of which imports failed and which succeeded

### PR DESCRIPTION
**Pull request by Pughal77**
Import Command now checks if the following parameters exist in the first row of a csv file: Name, phone, email and address.
importCommandParser also checks if the file Path given has the '.csv' file extension at the end of its path. This so that 
and importCommand objects is only created when the file given is a csv file, reducing the number of bugs.
Moreover, the utility function readCsv also throws a DataLoadingException if the file is not found with the given path.

fixes #165

Import Command also has a new feature where upon successful import, a report is shown showing the number of successful imports and unsuccessful imports

fixes #167

### CODE REVIEW

**Review by Zer0Legion — COMMENTED** [review]
Good change. Hope to see further fixes to the error message

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 1]
```diff
@@ -51,4 +58,24 @@ public static List<Map<String, String>> parseData(List<String[]> rows) {
...
         return data;
     }
+
+    /**
+     * Checks if the compulsory parameters are present in the header of the csv file.
+     * @param compulsoryParameters
+     * @param header
+     * @throws DataLoadingException
+     */
+    public static void checkCompulsoryParameters(String[] compulsoryParameters, String[] header)
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:68]: Nice abstraction

**Review by delishad21 — COMMENTED** [review]
Nice bugfix

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 2]
```diff
@@ -72,17 +73,36 @@ public ImportCommand(Path filePath) {
         this.filePath = filePath;
     }
 
+    /**
+     * Generates a report of the import process.
+     */
+    private String generateReport(int[] importResults) {
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:79]: Great job abstracting the report generation

File: src/main/java/seedu/address/logic/parser/ImportCommandParser.java [hunk 3]
```diff
@@ -29,8 +31,9 @@ public ImportCommand parse(String args) throws ParseException {
         }
 
         Path path = ParserUtil.parseFilePath(argMultimap.getValue(PREFIX_IMPORT).orElse(""));
+
         if (!isCsvFile(path)) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ImportCommand.MESSAGE_USAGE));
+            throw new ParseException(String.format(MESSAGE_NOT_CSV, path.toString()));
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/parser/ImportCommandParser.java:36]: Great job customizing the error messages

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 4]
```diff
@@ -72,17 +73,36 @@ public ImportCommand(Path filePath) {
...
+        int successfulImports = importResults[0];
+        int unsuccessfulImports = importResults[1];
+        return String.format(MESSAGE_IMPORT_SUCCESS, filePath.toString()) + "\n"
+            + String.format("Successful imports: %d\n", successfulImports)
+            + String.format("Unsuccessful imports: %d\n", unsuccessfulImports)
+            + errorMsgs;
+    }
+
+    private void generateErrorReport(Exception e) {
+        errorMsgs += e.getMessage() + "\n";
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:89]: Might wanna consider how you should change the AddCommandParser to ensure you highlight missing parameters.

**Review by jayllo-c — COMMENTED** [review]
Definitely a much needed update to import to remove known bugs!

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 5]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
-    public static List<Map<String, String>> readCsvFile(Path filePath) throws DataLoadingException {
+    public static Pair<Optional<List<Map<String, String>>>, String> readCsvFile(
+            Path filePath, HashSet<String> compulsoryParameters, HashSet<String> optionalParameters)
+            throws IOException {
+        List<Map<String, String>> data = null;
+        Optional<List<Map<String, String>>> nullableData = Optional.empty();
+        String errorMsgs = "";
         try {
             CSVReader reader = new CSVReaderBuilder(new FileReader(filePath.toString())).build();
+            List<String> headers = List.of(reader.readNext()); // first line should be headers
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:72]: Good abstraction to abstract the processing the headers

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 6]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
+            List<Integer> columnsToSkip = coloumnsToSkip(headers, compulsoryParameters, optionalParameters);
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:73]: Seems to be a innocent spelling mistake but might cascade since the intended spelling is different. Might want to consider changing this

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 7]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
             List<String[]> rows = reader.readAll();
-            return parseData(rows);
-        } catch (IOException | CsvException e) {
-            throw new DataLoadingException(e);
+            Pair<List<Map<String, String>>, String> result = parseData(rows, headers, columnsToSkip);
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:75]: Interesting, seems like you wanted to return two items and opted to do it through returning it in pairs. I wonder if this breaks any OOP rules. Perhaps you should create a seperate class called CSVParseResult with attributes of data and error messages and have the parseData return a CSVParseResult object. This is refactorable in 1.4 so no hurry

File: src/main/java/seedu/address/commons/util/CsvUtil.java (hunk 6 above)
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:73]: seems like an innocent spelling mistake but it might cascade to further confusion if others use this method. Might be a good idea to rename the method

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 8]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
+            data = result.getKey();
+            errorMsgs = result.getValue();
+            nullableData = Optional.of(data);
+            return new Pair<>(nullableData, errorMsgs);
+        } catch (DataLoadingException | CsvException e) {
+            return new Pair<>(nullableData, e.getMessage());
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:81]: The return type of this function is a little complicated. As mentioned in a previous comment, it might be a good idea to abstract this (Including the fact that data might be empty) into a seperate class.

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 9]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
+     * @param optionalParameters
+     * @return coloumnsToSkip
+     * @throws DataLoadingException
+     */
+    public static List<Integer> coloumnsToSkip(
+            List<String> headers, HashSet<String> compulsoryParameters, HashSet<String> optionalParameters)
+            throws DataLoadingException {
+        // first check if the compulsory parameters are present in the header
+        checkCompulsoryParameters(compulsoryParameters, headers);
+        return IntStream.range(0, headers.size())
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:99]: Good use of a stream function to obtain the accepted headers

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 10]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
+
+    /**
+     * Parses the data from the CSV file.
      * @param rows
+     * @param headers
+     * @param columnsToSkip
      * @return
      */
-    public static List<Map<String, String>> parseData(List<String[]> rows) {
+    public static Pair<List<Map<String, String>>, String> parseData(
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:112]: Good abstraction!

File: src/main/java/seedu/address/commons/util/CsvUtil.java [hunk 11]
```diff
@@ -36,39 +42,121 @@ public class CsvUtil {
...
+        return new Pair<>(data, errorMsgs.toString());
     }
 
+    /**
+     * Checks if the compulsory parameters are present in the header of the csv file.
+     * @param compulsoryParameters
+     * @param headers
+     * @throws DataLoadingException
+     */
+    public static void checkCompulsoryParameters(HashSet<String> compulsoryParameters, List<String> headers)
```
Comment (delishad21) [inline src/main/java/seedu/address/commons/util/CsvUtil.java:146]: Good idea to abstract out this functionality as well

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 12]
```diff
@@ -68,17 +81,68 @@ public ImportCommand(Path filePath) {
         this.filePath = filePath;
     }
 
+    /**
+     * Generates a report of the import process.
+     */
+    private String generateReport() {
```
Comment (delishad21) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:87]: Very comprehensive error report. Well done!

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 13]
```diff
@@ -68,17 +81,68 @@ public ImportCommand(Path filePath) {
...
+    private void generateErrorReportFromAddingPersons(Exception e, int index) {
+        errorMsgsFromAddingPersons += String.format("Person %s: ", index) + e.getMessage() + "\n";
+    }
+
+    private void generateErrorReportFromReadingCsv(DataLoadingException e) {
+        errorMsgsFromReadingCsv += e.getMessage() + "\n";
+    }
+
     @Override
     public CommandResult execute(Model model) throws CommandException {
```
Comment (delishad21) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:126]: Short execute method that has most of the complicated functionality abstracted away. Become the complicated return types for the data and error report, I think this is very well done.

**Review by delishad21 — COMMENTED** [review]
Generally very well implemented. Covered most of our tracks and throws a very comprehensive error message when something goes wrong.

File: src/main/java/seedu/address/commons/util/CsvUtil.java (hunk 6 above)
Comment (delishad21) [reply src/main/java/seedu/address/commons/util/CsvUtil.java:73]: coloumnsToSkip

Comment (jayllo-c) [reply src/main/java/seedu/address/commons/util/CsvUtil.java]: Could be more thorough on the checking of spelling issues

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 14]
```diff
@@ -30,20 +35,28 @@ public class ImportCommand extends Command {
...
+            + "Example: " + COMMAND_WORD + PREFIX_IMPORT + "C:usr/lib/text.csv";
+    private static final String MESSAGE_IMPORT_SUCCESS = "Imported Persons successfully!\n";
     private final Path filePath;
     private final AddCommandParser addCommandParser = new AddCommandParser();
 
     /**
      * Represents the order of the data that should be parsed into the addCommandParser
      */
-    private final String[] header = {"name", "phone", "email", "address", "matric", "reflection", "studio", "tags"};
+    private final HashSet<String> compulsoryParameters =
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:50]: Good separation of the compulsory and optional params

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 15]
```diff
@@ -68,17 +81,68 @@ public ImportCommand(Path filePath) {
...
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        Pair<Integer, Integer> importResults;
         try {
-            List<Map<String, String>> personsData = readCsvFile(filePath);
-            addToModel(model, personsData);
-        } catch (DataLoadingException e) {
-            throw new CommandException(String.format(MESSAGE_DATA_LOAD_ERROR, filePath));
+            Pair<Optional<List<Map<String, String>>>, String> result =
```
Comment (jayllo-c) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:130]: execute command is well abstracted
