### PR TITLE
bug fix: prevent execution of find command with duplicated prefixes present

### LINKED ISSUE #391: Able to execute find command with multiple repeated prefixes
e.g. `find n|a n|b`

Should not be able to execute this.

### PR DESCRIPTION
**Pull request by jayllo-c**
Fixes #391

Currently, the find command does not check that there are duplicate
prefixes present in the input provided by the user.

This is problematic because it allows the find command to accept
multiple duplicate prefixes despite the command being documented to
only accept one single prefix.

An example is `find n|alice n|bob`
* Expected behaviour: throw an error indicating more than one prefix
is used, similar to how `edit` and `add` behave in the presence of duplicate prefixes.
* Actual behaviour: finds persons containing bob, completely skips past alice.

This is incorrect behaviour which causes an incorrect result to be shown to the user.

Let's rectify this problem by using the in-built duplicate verifier to
properly handle the issue of duplicate prefixes.

Doing so will resolve the bug whilst reusing pre-existing code.

### CODE REVIEW

**Review by Zer0Legion — COMMENTED** [review]
Good spot! This fix prevents a pesky bug from sneaking in

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -22,6 +32,10 @@ public FindCommand parse(String args) throws ParseException {
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, FindCommand.ACCEPTED_PREFIXES);
 
+        argMultimap.verifyNoDuplicatePrefixesFor(
```
Comment (delishad21) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:35]: Good catch!

**Review by delishad21 — COMMENTED** [review]
Good bugfix, will prevent the app from misbehaving
