### PR TITLE
Fix: Save file loads properly when persons have empty optional parameters

### LINKED ISSUE #180: bug: Save file cannot be loaded when any person has empty optional parameters
Current behaviour:
When a person is saved without optional parameter (matric num/reflection/tutorial) The application saves empty strings into the json save file. 

When the app is rebooted and it tries to load the save file, the app throws an error as empty strings are not allowed for these parameters. The app then starts with an empty addressbook.

Expected behaviour: 
The app detects the empty string in the json file as an indicator that this person does not have that optional parameter included and loads up a person into the addressbook appropriately.

### PR DESCRIPTION
**Pull request by jayllo-c**
Fixes #180

Currently, when either Matric, Studio or Reflection fields are empty
i.e. "", the code will throw an `IllegalValueException`.

This behaviour is incorrect because these fields are optional and should
not need to be filled.

Let's ensure that the saved data is loaded correctly when the optional
parameters are empty whilst ensuring that the code ensures only valid
values are allowed.

Doing so will ensure that the code will achieve the correct behaviour,
only throwing an `IllegalValueException` when it is appropriate.

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java [hunk 1]
```diff
@@ -114,13 +114,13 @@ public Person toModelType() throws IllegalValueException {
...
-        if (!Matric.isValidMatric(matric)) {
+        if (!Matric.isValidConstructorParam(matric)) {
             throw new IllegalValueException(Matric.MESSAGE_CONSTRAINTS);
         }
-        if (!Reflection.isValidReflection(reflection)) {
+        if (!Reflection.isValidConstructorParam(reflection)) {
             throw new IllegalValueException(Reflection.MESSAGE_CONSTRAINTS);
         }
-        if (!Studio.isValidStudio(studio)) {
+        if (!Studio.isValidConstructorParam(studio)) {
```
Comment (Zer0Legion) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:123]: Good catch James! Just checking to ensure that this will not allow users themselves to create blank matric/studio/reflection fields as it was a problem I have experienced before?

Comment (delishad21) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:123]: Nice catch, this massive bug would have prevented our users from using this application properly. Lets continue to keep our application bug free!

**Review by delishad21 — COMMENTED** [review]
Good Job on this change

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java (hunk 1 above)
Comment (danielleloh) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:123]: nice catch :)

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java [hunk 2]
```diff
@@ -114,13 +114,13 @@ public Person toModelType() throws IllegalValueException {
         if (!Address.isValidAddress(address)) {
             throw new IllegalValueException(Address.MESSAGE_CONSTRAINTS);
         }
-        if (!Matric.isValidMatric(matric)) {
+        if (!Matric.isValidConstructorParam(matric)) {
```
Comment (Pughal77) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:117]: Nice catch! This would ensure that there are lesser bugs in the program

**Review by Pughal77 — COMMENTED** [review]
Nice clean implementation
