### PR TITLE
Add unit tests for exams and scores and Fix bugs

### LINKED ISSUE #232: Bug: AddExamCommand MESSAGE_USAGE is incorrect
Replace the current MESSAGE_USAGE with the following

```
 public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds an exam to the address book. "
            + "Parameters: EXAM_NAME EXAM_DETAILS\n"
            + "Example: " + COMMAND_WORD + " "
            + PREFIX_NAME + "Midterms " + PREFIX_SCORE + "100";
```

### LINKED ISSUE #233: Add Unit Tests for Exam and Score Commands

### PR DESCRIPTION
**Pull request by delishad21**
Currently, the code coverage for the exams and scores commands is abysmal. Lets add tests to improve code coverage for that portion of the code. 

Fixes #233 
Fixes #232

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/SelectExamCommandParserTest.java
Comment (Zer0Legion) [inline src/test/java/seedu/address/logic/parser/SelectExamCommandParserTest.java:1]: Comprehensive testing with short and neat test cases.

File: src/test/java/seedu/address/model/AddressBookTest.java [hunk 1]
```diff
@@ -50,27 +52,55 @@ public void resetData_withDuplicatePersons_throwsDuplicatePersonException() {
...
                 .build();
         List<Person> newPersons = Arrays.asList(ALICE, editedAlice);
-        AddressBookStub newData = new AddressBookStub(newPersons);
+        AddressBookStub newData = new AddressBookStub(newPersons, Collections.emptyList());
 
         assertThrows(DuplicatePersonException.class, () -> addressBook.resetData(newData));
     }
 
+    @Test
+    public void resetData_withDuplicateExams_throwsDuplicateExamException() {
```
Comment (Zer0Legion) [inline src/test/java/seedu/address/model/AddressBookTest.java:61]: good catch

File: src/test/java/seedu/address/model/AddressBookTest.java [hunk 2]
```diff
@@ -79,27 +109,94 @@ public void hasPerson_personWithSameIdentityFieldsInAddressBook_returnsTrue() {
...
+
     /**
      * A stub ReadOnlyAddressBook whose persons list can violate interface constraints.
      */
     private static class AddressBookStub implements ReadOnlyAddressBook {
         private final ObservableList<Person> persons = FXCollections.observableArrayList();
         private final ObservableList<Exam> exams = FXCollections.observableArrayList();
 
-        AddressBookStub(Collection<Person> persons) {
+        AddressBookStub(Collection<Person> persons, Collection<Exam> exams) {
```
Comment (Zer0Legion) [inline src/test/java/seedu/address/model/AddressBookTest.java:197]: I like the use of stubs here, this simplifies the testing process much more
