### PR TITLE
Bug fix:  Ensure correct naming for Boolean methods in find functionality

### LINKED ISSUE #308: Ensure methods around the find functionality are named correctly
* double-check boolean methods have been named appropriately

### PR DESCRIPTION
**Pull request by jayllo-c**
Fixes #308

Currently the find functionality works as intended.
However, two Boolean methods in the
`PersonDetailContainsKeywordAndExamPredicate.java` file were incorrectly
named as they do not sound like Booleans.

This has to be changed immediately as it violates the coding standards
for style.

Let's rename these methods correctly, following the coding conventions.

By doing so, we can ensure that our code keeps to the expected
coding standard.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicate.java [hunk 1]
```diff
@@ -34,9 +34,9 @@ public PersonDetailContainsKeywordAndExamPredicate(Prefix prefix, String keyword
     @Override
     public boolean test(Person person) {
         if (PREFIX_LESS_THAN.equals(prefix)) {
-            return trueIfLT(person);
+            return hasScoreLessThanKeyword(person);
```
Comment (danielleloh) [inline src/main/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicate.java:37]: nice catch to improve code quality!

**Review by delishad21 — COMMENTED** [review]
Good catch!
